"""empty message

Revision ID: e47f145de306
Revises: 565b551e39a5
Create Date: 2017-02-24 10:41:27.089569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47f145de306'
down_revision = '565b551e39a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counselors_merit_badges',
    sa.Column('counselor_id', sa.Integer(), nullable=True),
    sa.Column('merit_badge_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['counselor_id'], ['counselors.id'], ),
    sa.ForeignKeyConstraint(['merit_badge_id'], ['merit_badges.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counselors_merit_badges')
    # ### end Alembic commands ###
